CodeSystem: NomivacEsquemaCS
Id: NomivacEsquemaCS
Title: "Esquemas de Vacunacion para NOMIVAC"
Description: "Esquemas de Vacunacion para NOMIVAC"
* ^url = "http://fhir.msal.gob.ar/core/CodeSystem/NomivacEsquemaCS"
* ^version = "0.5.0"
* ^name = "NomivacEsquemaCS"
* ^title = "Esquemas de Vacunacion para NOMIVAC"
* ^status = #active
* ^date = "2021-07-18T16:43:39-03:00"
* ^publisher = "DNSIS - Ministerio de Salud - Rep. Argentina / HL7 Argentina"
* ^contact[0].name = "DNSIS - Ministerio de Salud - Rep. Argentina / HL7 Argentina"
* ^contact[=].telecom[0].system = #url
* ^contact[=].telecom[=].value = "https://www.argentina.gob.ar/salud/digital"
* ^contact[=].telecom[+].system = #email
* ^contact[=].telecom[=].value = "privadadngiss@msal.gov.ar"
* ^experimental = false
* ^language = #es-AR

* #63 "Recién Nacido Hepatitis B Calendario Nacional"
* #69 "Alterno VPH Bivalente Otros"
* #70 "Personal de Salud Hepatitis B Personal de Salud"
* #71 "Regular Fiebre Amarilla Calendario Nacional"
* #72 "Viaje a Zona Endémica Fiebre Amarilla Viaje a Zona Endémica"
* #74 "Regular Neumococo Conjugada VCN 13 Calendario Nacional"
* #75 "Regular Quintuple Calendario Nacional"
* #76 "Regular Cuádruple Bacteriana Calendario Nacional"
* #77 "Regular Triple Viral Calendario Nacional"
* #78 "Calendario Nacional Antigripal Calendario Nacional"
* #79 "Embarazo Antigripal Embarazo"
* #81 "Personal de Salud Antigripal Personal de Salud"
* #82 "Regular Hepatitis A Calendario Nacional"
* #83 "Regular Triple Bacteriana Celular Calendario Nacional"
* #86 "RegulaR Doble Bacteriana Calendario Nacional"
* #87 "Embarazo Doble Bacteriana Embarazo"
* #88 "Puerperio Doble Viral Puerperio"
* #89 "Regular Fiebre Hemorrágica Argentina Calendario Nacional"
* #90 "Residencia en Zona Endémica Fiebre Hemorrágica Argentina Zona Endemica"
* #99 "Regular OPV Sabin Calendario Nacional"
* #100 "Atrasado OPV Sabin Calendario Nacional"
* #104 "Incompleto Triple Viral Calendario Nacional"
* #105 "Atrasado BCG Calendario Nacional"
* #108 "Factores de Riesgo Hepatitis B Personas con factores de riesgo"
* #109 "Regular Hepatitis B Calendario Nacional"
* #110 "Regular Triple Bacteriana Acelular Calendario Nacional"
* #112 "Personal de Salud Triple Bacteriana Acelular Personal de Salud"
* #113 "Embarazo Triple Bacteriana Acelular Embarazo"
* #116 "Atrasado Cuádruple Bacteriana Calendario Nacional"
* #121 "Incompleto Doble Bacteriana Calendario Nacional"
* #123 "Puerperio Antigripal Puerperio"
* #124 "Regular 9 a 64 años con F de Riesgo Antigripal Calendario Nacional"
* #125 "Personas con factores de riesgo Hepatitis A Personas con factores de riesgo"
* #126 "Niños con Factores de Riesgo Neumococo Polisacarida 23 Valente Huéspedes Especiales"
* #127 "Regular Varicela Calendario Nacional"
* #128 "Atrasado Hepatitis A Calendario Nacional"
* #129 "Niños de 2 Años Adolescentes y Adultos Meningocócica Tetravalente Conjugada Personas con factores de riesgo"
* #131 "Personas con factores de riesgo IPV SALK Personas con factores de riesgo"
* #132 "Adultos Doble Viral Calendario Nacional"
* #134 "Esquema de Excepción BCG Otros"
* #135 "Esquema de Excepción Cuádruple Bacteriana Otros"
* #136 "Esquema de Excepción Doble Bacteriana Otros"
* #137 "Esquema de Excepción Doble Viral Otros"
* #138 "Esquema de Excepción Fiebre Amarilla Otros"
* #139 "Esquema de Excepción Fiebre Hemorrágica Argentina Otros"
* #140 "Esquema de Excepción Hepatitis A Otros"
* #141 "Esquema de Excepción Hepatitis B Otros"
* #142 "Esquema de Excepción Antigripal Otros"
* #143 "Esquema de Excepción Neumococo Polisacarida 23 Valente Otros"
* #144 "Esquema de Excepción Neumococo Conjugada VCN 13 Otros"
* #145 "Esquema de Excepción Quintuple Otros"
* #146 "Esquema de Excepción IPV SALK Otros"
* #147 "Esquema de Excepción OPV Sabin Otros"
* #148 "Esquema de Excepción Triple Bacteriana Acelular Otros"
* #149 "Esquema de Excepción Triple Bacteriana Celular Otros"
* #150 "Esquema de Excepción Triple Viral Otros"
* #151 "Esquema de Excepción VPH Bivalente Otros"
* #152 "Esquema de Excepción Meningocócica Tetravalente Conjugada Otros"
* #153 "Esquema de Excepción Antimeningocócica Tetravalente Polisacárida Otros"
* #154 "Esquema de Excepción Varicela Otros"
* #155 "Esquema de Excepción Rotavirus Monovalente Otros"
* #158 "Regular Rotavirus Monovalente Calendario Nacional"
* #159 "Regular Rotavirus Pentavalente Personas con factores de riesgo"
* #160 "Esquema de Excepción Rotavirus Pentavalente Otros"
* #161 "Regular Antimeningocócica Tetravalente Polisacárida Brote"
* #162 "Esquema de Excepción Leptospirosis Otros"
* #163 "Regular Leptospirosis Personas con factores de riesgo"
* #164 "Esquema de Excepción Fiebre Tifoidea Parenteral Otros"
* #165 "Regular Fiebre Tifoidea Parenteral Personas con factores de riesgo"
* #166 "Esquema de Excepción Fiebre Tifoidea Oral Otros"
* #167 "Regular Fiebre Tifoidea Oral Personas con factores de riesgo"
* #168 "Esquema de Excepción Colera Oral Otros"
* #169 "Regular Adultos Colera Oral Zona Endemica"
* #170 "Regular Niños Colera Oral Zona Endemica"
* #171 "Esquema de Excepción Colera Parenteral Otros"
* #172 "Regular Pre Exposición Antirrábica Cultivo en Lineas Celulares Profilaxis Preexposicion"
* #173 "Regular Pre Exposición Antirrábica Fuenzalida Palacios Profilaxis Preexposicion"
* #174 "Esquema de Excepción Antirrábica Fuenzalida Palacios Otros"
* #175 "Esquema de Excepción Antirrábica Cultivo en Lineas Celulares Otros"
* #176 "Regular Post Exposición de Animal Observado Antirrábica Fuenzalida Palacios Profilaxis Post Exposición - Contacto con Animal Observado"
* #177 "Regular Post Exposición Animal Muerto o Desaparecido Antirrábica Fuenzalida Palacios Profilaxis Post Exposición - Contacto con Animal Muerto o Desaparecido"
* #178 "Regular Post Exposición de Animal Observado Antirrábica Cultivo en Lineas Celulares Profilaxis Post Exposición - Contacto con Animal Observado"
* #179 "Regular Post Exposición Animal Muerto o Desaparecido Antirrábica Cultivo en Lineas Celulares Profilaxis Post Exposición - Contacto con Animal Muerto o Desaparecido"
* #180 "Regular 25 Meses a 8 Años con F Riesgo Antigripal Calendario Nacional"
* #181 "Mayores de 65 Años Antigripal Mayor de 65 años"
* #182 "Atrasado Doble Bacteriana Calendario Nacional"
* #183 "Atrasado Neumococo Conjugada VCN 13 Calendario Nacional"
* #184 "Atrasado Quintuple Calendario Nacional"
* #185 "Prematuro Séxtuple Acelular Personas con factores de riesgo"
* #186 "Esquema de Excepción Séxtuple Acelular Otros"
* #188 "Prematuros BCG Personas con factores de riesgo"
* #189 "Prematuro Triple Bacteriana Acelular Pediátrica Personas con factores de riesgo"
* #190 "Esquema de Excepción Triple Bacteriana Acelular Pediátrica Otros"
* #191 "Niños y Adultos con Factores de Riesgo Neumococo Polisacarida 23 Valente Huéspedes Especiales"
* #193 "Mayores de 65 Años Neumococo Polisacarida 23 Valente Personas con factores de riesgo"
* #196 "Regular Niños Meningocócica Monovalente Conjugada Grupo C Personas con factores de riesgo"
* #197 "Esquema de Excepcion Meningocócica Monovalente Conjugada Grupo C Otros"
* #198 "Regular Quintuple Acelular Personas con factores de riesgo"
* #199 "Esquema de Excepción Quintuple Acelular Otros"
* #200 "Regular Hepatitis A y B Personas con factores de riesgo"
* #201 "Esquema de Excepción Hepatitis A y B Otros"
* #202 "Regular Haemophilus Influenzae tipo b Personas con factores de riesgo"
* #203 "Esquema de Excepción Haemophilus Influenzae tipo b Otros"
* #204 "Regular Antimeningocócica Bivalente Conjugada BC Personas con factores de riesgo"
* #205 "Esquema de Excepción Antimeningocócica Bivalente Conjugada BC Otros"
* #206 "Regular Antimeningocócica Bivalente Conjugada AC Personas con factores de riesgo"
* #207 "Esquema de Excepción Antimeningocócica Bivalente Conjugada AC Otros"
* #208 "Esquema de Excepción Cuadruple Acelular DPaT e IPV Otros"
* #209 "Regular Cuadruple Acelular DPaT e IPV Calendario Nacional"
* #210 "Niños de 2 a 6 Meses Meningocócica Tetravalente Conjugada Personas con factores de riesgo"
* #211 "Niños de 6 a 23 Meses Meningocócica Tetravalente Conjugada Personas con factores de riesgo"
* #212 "IMPORTACION BCG IMPORTACION"
* #213 "IMPORTACION Cuádruple Bacteriana IMPORTACION"
* #214 "IMPORTACION Doble Bacteriana IMPORTACION"
* #215 "IMPORTACION Doble Viral IMPORTACION"
* #216 "IMPORTACION Fiebre Amarilla IMPORTACION"
* #217 "IMPORTACION Fiebre Hemorrágica Argentina IMPORTACION"
* #218 "IMPORTACION Hepatitis A IMPORTACION"
* #219 "IMPORTACION Hepatitis B IMPORTACION"
* #220 "IMPORTACION Antigripal IMPORTACION"
* #221 "IMPORTACION Neumococo Polisacarida 23 Valente IMPORTACION"
* #222 "IMPORTACION Neumococo Conjugada VCN 13 IMPORTACION"
* #223 "IMPORTACION Quintuple IMPORTACION"
* #224 "IMPORTACION IPV SALK IMPORTACION"
* #225 "IMPORTACION OPV Sabin IMPORTACION"
* #226 "IMPORTACION Triple Bacteriana Acelular IMPORTACION"
* #227 "IMPORTACION Triple Bacteriana Celular IMPORTACION"
* #228 "IMPORTACION Triple Viral IMPORTACION"
* #229 "IMPORTACION VPH Bivalente IMPORTACION"
* #230 "IMPORTACION Meningocócica Tetravalente Conjugada IMPORTACION"
* #231 "IMPORTACION Antimeningocócica Tetravalente Polisacárida IMPORTACION"
* #232 "IMPORTACION Varicela IMPORTACION"
* #233 "IMPORTACION Rotavirus Monovalente IMPORTACION"
* #234 "IMPORTACION Rotavirus Pentavalente IMPORTACION"
* #235 "IMPORTACION Leptospirosis IMPORTACION"
* #236 "IMPORTACION Fiebre Tifoidea Parenteral IMPORTACION"
* #237 "IMPORTACION Fiebre Tifoidea Oral IMPORTACION"
* #238 "IMPORTACION Colera Oral IMPORTACION"
* #239 "IMPORTACION Colera Parenteral IMPORTACION"
* #240 "IMPORTACION Antirrábica Fuenzalida Palacios IMPORTACION"
* #241 "IMPORTACION Antirrábica Cultivo en Lineas Celulares IMPORTACION"
* #242 "IMPORTACION Séxtuple Acelular IMPORTACION"
* #243 "IMPORTACION Triple Bacteriana Acelular Pediátrica IMPORTACION"
* #244 "IMPORTACION Meningocócica Monovalente Conjugada Grupo C IMPORTACION"
* #245 "IMPORTACION Quintuple Acelular IMPORTACION"
* #246 "IMPORTACION Hepatitis A y B IMPORTACION"
* #247 "IMPORTACION Haemophilus Influenzae tipo b IMPORTACION"
* #248 "IMPORTACION Antimeningocócica Bivalente Conjugada BC IMPORTACION"
* #249 "IMPORTACION Antimeningocócica Bivalente Conjugada AC IMPORTACION"
* #250 "IMPORTACION Cuadruple Acelular DPaT e IPV IMPORTACION"
* #251 "Esquema de Excepción Neumococo Conjugada Otros"
* #252 "Alterno Neumococo Conjugada Personas con factores de riesgo"
* #253 "Esquema de Excepción VPH Cuadrivalente Otros"
* #254 "IMPORTACION VPH Cuadrivalente IMPORTACION"
* #255 "Esquema de Excepción Antitetánica Otros"
* #256 "IMPORTACION Antitetánica IMPORTACION"
* #257 "Alterno Inicio mayor e igual a 14 años VPH Cuadrivalente Calendario Nacional"
* #258 "IMPORTACION Neumococo Conjugada IMPORTACION"
* #259 "Anual 6 a 24 Meses Antigripal Calendario Nacional"
* #260 "Anual 25 Meses a 8 Años con F Riesgo Antigripal Calendario Nacional"
* #261 "Personal Esencial Antigripal Personal Esencial"
* #262 "Personas con factores de riesgo VPH Cuadrivalente Personas con factores de riesgo"
* #263 "Personas con factores de riesgo VPH Bivalente Personas con factores de riesgo"
* #264 "Prematuro Palivizumab Personas con factores de riesgo"
* #265 "Displasia Broncopulmonar Palivizumab Personas con factores de riesgo"
* #266 "Cardiopatía congénita Palivizumab Personas con factores de riesgo"
* #267 "Esquema de Excepción Palivizumab Otros"
* #268 "IMPORTACION Palivizumab IMPORTACION"
* #269 "Recien Nacido Inmunoglobulina Antihepatitis B Personas con factores de riesgo"
* #270 "Post exposición Inmunoglobulina Antirrábica Humana Personas con factores de riesgo"
* #271 "Embarazo Inmunoglobulina Antivaricela Zoster Embarazo"
* #272 "Inmunocomprometidos Inmunoglobulina Antivaricela Zoster Inmunocomprometido"
* #273 "Neonatos Inmunoglobulina Antivaricela Zoster Personas con factores de riesgo"
* #274 "Post exposición Inmunoglobulina Hiperinmune Antitetánica Personas con factores de riesgo"
* #275 "Post exposición en inmunocomprometido Inmunoglobulina Polivalente Inmunocomprometido"
* #276 "Post exposición en embarazo Inmunoglobulina Polivalente Embarazo"
* #277 "Post exposición Inmunoglobulina Antihepatitis B Personas con factores de riesgo"
* #278 "Personas con factores de riesgo Varicela Personas con factores de riesgo"
* #279 "Regular VPH Bivalente Otros"
* #280 "Regular VPH Cuadrivalente Calendario Nacional"
* #281 "Mayores de 5 años con Factores de Riesgo Neumococo Conjugada VCN 13 Personas con factores de riesgo"
* #283 "Mayores de 2 Años con Factores de Riesgo Neumococo Polisacarida 23 Valente Personas con factores de riesgo"
* #284 "Personal de Salud Varicela Personal de Salud"
* #285 "Regular Adultos Meningocócica Monovalente Conjugada Grupo C Personas con factores de riesgo"
* #286 "Niños de 3 a 15 Meses Meningocócica Tetravalente Conjugada Personas con factores de riesgo"
* #287 "Niños de 11 Años Meningocócica Tetravalente Conjugada Personas con factores de riesgo"
* #288 "Secuencial IPV SALK Calendario Nacional"
* #289 "Secuencial OPV Sabin Calendario Nacional"
* #290 "Embarazo Hepatitis B Embarazo"
* #292 "Huéspedes Especiales Neumococo Conjugada VCN 13 Huéspedes Especiales"
* #293 "Regular Doble Bacteriana Calendario Nacional"
* #294 "IMPORTACION Inmunoglobulina Polivalente IMPORTACION"
* #295 "IMPORTACION Inmunoglobulina Hiperinmune Antitetánica IMPORTACION"
* #296 "IMPORTACION Inmunoglobulina Antivaricela Zoster IMPORTACION"
* #297 "IMPORTACION Inmunoglobulina Antirrábica Humana IMPORTACION"
* #298 "IMPORTACION Inmunoglobulina Antihepatitis B IMPORTACION"
* #299 "Esquema de Excepción Inmunoglobulina Polivalente Otros"
* #300 "Esquema de Excepción Inmunoglobulina Hiperinmune Antitetánica Otros"
* #301 "Esquema de Excepción Inmunoglobulina Antivaricela Zoster Otros"
* #302 "Esquema de Excepción Inmunoglobulina Antirrábica Humana Otros"
* #303 "Esquema de Excepción Inmunoglobulina Antihepatitis B Otros"
* #304 "Regular Lactantes Meningocócica Tetravalente Conjugada Calendario Nacional"
* #305 "Regular Adolescentes Meningocócica Tetravalente Conjugada Calendario Nacional"
* #306 "Inmunodeficiencia Meningocócica Tetravalente Conjugada Inmunodeficiencia"
* #307 "Personal de Salud Meningocócica Tetravalente Conjugada Personal de Salud"
* #308 "Menores de 5 años con Factores de Riesgo Neumococo Conjugada VCN 13 Calendario Nacional"
* #309 "Conviviente Inmunocomprometido Varicela Conviviente Inmunocomprometido"
* #310 "Conviviente inmunocomprometido Triple Bacteriana Acelular Conviviente Inmunocomprometido"
* #311 "Conviviente Inmunocomprometido Antigripal Conviviente Inmunocomprometido"
* #312 "Conviviente Inmunocomprometido 9 a 64 años Antigripal Conviviente Inmunocomprometido"
* #317 "Inmunodeficiencia Neumococo Conjugada VCN 13 Inmunodeficiencia"
* #318 "Inmunodeficiencia Neumococo Polisacarida 23 Valente Inmunodeficiencia"
* #319 "Asplénico Haemophilus Influenzae tipo b Asplénico"
* #320 "Asplénico Meningocócica Tetravalente Conjugada Asplénico"
* #321 "Menores de 6 meses Meningococica Multicomponente del grupo B Personas con factores de riesgo"
* #322 "Mayores de 6 meses Meningococica Multicomponente del grupo B Personas con factores de riesgo"
* #331 "Esquema de Excepción Meningococica Multicomponente del grupo B Otros"
* #332 "IMPORTACION Meningococica Multicomponente del grupo B IMPORTACION"
* #333 "Cardiológico Antigripal Cardiológico"
* #334 "Diabético Antigripal Diabético"
* #335 "Inmunocomprometido Antigripal Inmunocomprometido"
* #336 "Inmunodeficiencia Antigripal Inmunodeficiencia"
* #337 "Obesidad Mórbida Antigripal Obesidad Mórbida"
* #338 "Respiratorio Antigripal Respiratorio"
* #339 "6 a 24 meses VIRAFLU Pediátrica Calendario Nacional"
* #340 "2 a 8 años VIRAFLU Pediátrica Personas con factores de riesgo"
* #341 "Embarazo VIRAFLU Pediátrica Embarazo"
* #342 "Puerperio VIRAFLU Pediátrica Puerperio"
* #343 "9 a 64 años VIRAFLU Pediátrica Adultos con Factores de Riesgo"
* #344 "Mayores de 65 años VIRAFLU Pediátrica Mayor de 65 años"
* #345 "Personal de Salud VIRAFLU Pediátrica Personal de Salud"
* #346 "Personal Esencial VIRAFLU Pediátrica Personal Esencial"
* #347 "Embarazo VIRAFLU Adultos Embarazo"
* #348 "Puerperio VIRAFLU Adultos Puerperio"
* #349 "6 a 24 meses VIRAFLU Adultos Calendario Nacional"
* #350 "2 a 8 años VIRAFLU Adultos Personas con factores de riesgo"
* #351 "9 a 64 años VIRAFLU Adultos Adultos con Factores de Riesgo"
* #352 "Mayores de 65 años VIRAFLU Adultos Mayor de 65 años"
* #353 "Personal de Salud VIRAFLU Adultos Personal de Salud"
* #354 "Personal Esencial VIRAFLU Adultos Personal Esencial"
* #355 "6 a 11 meses Triple Viral Campaña"
* #356 "Adicional Triple Viral Campaña"
* #357 "13 a 23 meses Triple Viral Campaña"
* #358 "2 años Triple Viral Campaña"
* #359 "3 años Triple Viral Campaña"
* #360 "4 años Triple Viral Campaña"
* #361 "Adicional para complemento Triple Viral Campaña"
* #362 "Mayor de 50 años Herpes Zoster Mayor de 50 años"
* #363 "3 a 64 años Antigripal Cuadrivalente Prescripción médica"
* #364 "Embarazo Antigripal Cuadrivalente Embarazo"
* #365 "Mayores de 65 años Antigripal Cuadrivalente Mayor de 65 años"
* #366 "Dosis 0 Triple Viral Campaña"
* #367 "Único Cuádruple Viral Prescripción médica"
* #368 "Esquema de Excepción Cuádruple Viral Otros"
* #369 "Adicional Doble Viral Campaña"
* #370 "Dosis 0 Doble Viral Campaña"
* #371 "6 a 11 meses Doble Viral Campaña"
* #372 "13 a 23 meses Doble Viral Campaña"
* #373 "2 años Doble Viral Campaña"
* #374 "3 años Doble Viral Campaña"
* #375 "4 años Doble Viral Campaña"
* #376 "Regular IPV SALK Calendario Nacional"
* #377 "Atrasado IPV SALK Calendario Nacional"
* #378 "Atrasado Varicela Calendario Nacional"
* #379 "Atrasado Triple Viral Calendario Nacional"
* #380 "Atrasado Triple Bacteriana Celular Calendario Nacional"
* #381 "Atrasado Triple Bacteriana Acelular Calendario Nacional"
* #382 "Atrasado Lactantes Meningocócica Tetravalente Conjugada Calendario Nacional"
* #383 "Atrasado Adolescente Meningocócica Tetravalente Conjugada Calendario Nacional"
* #384 "Atrasado VPH Cuadrivalente Calendario Nacional"
* #385 "Atrasado Fiebre Amarilla Calendario Nacional"
* #386 "7 a 14 años Triple Viral Campaña"
* #387 "7 a 14 años Doble Viral Campaña"
* #388 "15 a 24 años Triple Viral Campaña"
* #389 "25 a 44 años Triple Viral Campaña"
* #390 "Mayores a 45 años Triple Viral Campaña"
* #391 "15 a 24 años Doble Viral Campaña"
* #392 "25 a 44 años Doble Viral Campaña"
* #393 "Mayores a 45 años Doble Viral Campaña"
* #394 "Menor a 12 horas Hepatitis B Otros"
* #397 "Menor de 7 días BCG Otros"
* #398 "Menor de 1 año BCG Otros"
* #399 "2 meses Rotavirus Monovalente Otros"
* #400 "4 meses Rotavirus Monovalente Otros"
* #401 "2 meses IPV SALK Otros"
* #402 "4 meses IPV SALK Otros"
* #403 "6 meses IPV SALK Otros"
* #404 "Ingreso escolar IPV SALK Otros"
* #405 "3 meses Meningocócica Tetravalente Conjugada Otros"
* #406 "5 meses Meningocócica Tetravalente Conjugada Otros"
* #407 "15 meses Meningocócica Tetravalente Conjugada Otros"
* #408 "11 años Meningocócica Tetravalente Conjugada Otros"
* #409 "2 meses Quintuple Otros"
* #410 "4 meses Quintuple Otros"
* #411 "6 meses Quintuple Otros"
* #412 "15 a 18 meses Quintuple Otros"
* #413 "1 año Hepatitis A Otros"
* #414 "2 meses Neumococo Conjugada VCN 13 Otros"
* #415 "4 meses Neumococo Conjugada VCN 13 Otros"
* #416 "12 meses Neumococo Conjugada VCN 13 Otros"
* #417 "15 meses Varicela Otros"
* #418 "1 año Triple Viral Otros"
* #419 "Ingreso escolar Triple Viral Otros"
* #420 "Ingreso escolar Triple Bacteriana Celular Otros"
* #421 "11 años MUJERES VPH Cuadrivalente Otros"
* #422 "11 años VARONES VPH Cuadrivalente Otros"
* #423 "11 años Triple Bacteriana Acelular Otros"
* #424 "Embarazadas Triple Bacteriana Acelular Otros"
* #425 "1 año Fiebre Amarilla Otros"
* #426 "11 años Fiebre Amarilla Otros"
* #427 "Personal de Salud Meningococica Multicomponente del grupo B Personal de Salud"
* #428 "Inmunodeficiencia menor de 5 años Meningococica Multicomponente del grupo B Inmunodeficiencia"
* #429 "Inmunodeficiencia mayor de 5 años Meningococica Multicomponente del grupo B Inmunodeficiencia"
* #430 "Asplénico menor de 5 años Meningococica Multicomponente del grupo B Asplénico"
* #431 "Asplénico mayor de 5 años Meningococica Multicomponente del grupo B Asplénico"
* #432 "Déficit de complemento menor de 5 años Meningococica Multicomponente del grupo B Déficit de complemento"
* #433 "Déficit de complemento mayor de 5 años Meningococica Multicomponente del grupo B Déficit de complemento"
* #434 "Inmunodeficiencia menor de 5 años Meningocócica Tetravalente Conjugada Inmunodeficiencia"
* #435 "Inmunodeficiencia mayor de 5 años Meningocócica Tetravalente Conjugada Inmunodeficiencia"
* #436 "Asplénico menor de 5 años Meningocócica Tetravalente Conjugada Asplénico"
* #437 "Asplénico mayor de 5 años Meningocócica Tetravalente Conjugada Asplénico"
* #438 "Déficit de complemento menor de 5 años Meningocócica Tetravalente Conjugada Déficit de complemento"
* #439 "Déficit de complemento mayor de 5 años Meningocócica Tetravalente Conjugada Déficit de complemento"
* #440 "Personal de Salud Sputnik V COVID19 Instituto Gamaleya Personal de Salud"
* #441 "Personal Estratégico Sputnik V COVID19 Instituto Gamaleya Personal Estratégico"
* #442 "Personas de 60 o más años Sputnik V COVID19 Instituto Gamaleya Personas de 60 o más años"
* #443 "Personas de 18 a 59 años con Factores de Riesgo Sputnik V COVID19 Instituto Gamaleya Personas de 18 a 59 años con Factores de Riesgo"
* #444 "Esquema de Excepción Sputnik V COVID19 Instituto Gamaleya Otros"
* #445 "Personal de Salud COVISHIELD ChAdOx1nCoV COVID 19 Personal de Salud"
* #446 "Personal Estratégico COVISHIELD ChAdOx1nCoV COVID 19 Personal Estratégico"
* #447 "Personas de 60 o más años COVISHIELD ChAdOx1nCoV COVID 19 Personas de 60 o más años"
* #448 "Personas de 18 a 59 años con Factores de Riesgo COVISHIELD ChAdOx1nCoV COVID 19 Personas de 18 a 59 años con Factores de Riesgo"
* #449 "Esquema de Excepción COVISHIELD ChAdOx1nCoV COVID 19 Otros"
* #450 "Personal de Salud Sinopharm Vacuna SARSCOV 2 inactivada Personal de Salud"
* #451 "Personal Estratégico Sinopharm Vacuna SARSCOV 2 inactivada Personal Estratégico"
* #452 "Personas de 60 o más años Sinopharm Vacuna SARSCOV 2 inactivada Personas de 60 o más años"
* #453 "Personas de 18 a 59 años con Factores de Riesgo Sinopharm Vacuna SARSCOV 2 inactivada Personas de 18 a 59 años con Factores de Riesgo"
* #454 "Esquema de Excepción Sinopharm Vacuna SARSCOV 2 inactivada Otros"
* #455 "Personal de Salud Fluxvir adyuvantada Personal de Salud"
* #456 "Personal Esencial Fluxvir adyuvantada Personal Esencial"
* #457 "Mayores de 65 Años Fluxvir adyuvantada Mayor de 65 años"
* #458 "Calendario Nacional VIRAFLU Pediátrica Calendario Nacional"
* #464 "Conviviente Inmunocomprometido VIRAFLU Pediátrica Conviviente Inmunocomprometido"
* #465 "Cardiológico VIRAFLU Pediátrica Cardiológico"
* #466 "Diabético VIRAFLU Pediátrica Diabético"
* #467 "Inmunocomprometido VIRAFLU Pediátrica Inmunocomprometido"
* #468 "Inmunodeficiencia VIRAFLU Pediátrica Inmunodeficiencia"
* #469 "Obesidad Mórbida VIRAFLU Pediátrica Obesidad Mórbida"
* #470 "Respiratorio VIRAFLU Pediátrica Respiratorio"
* #471 "Calendario Nacional VIRAFLU Adultos Calendario Nacional"
* #477 "Conviviente Inmunocomprometido VIRAFLU Adultos Conviviente Inmunocomprometido"
* #478 "Cardiológico VIRAFLU Adultos Cardiológico"
* #479 "Diabético VIRAFLU Adultos Diabético"
* #480 "Inmunocomprometido VIRAFLU Adultos Inmunocomprometido"
* #481 "Inmunodeficiencia VIRAFLU Adultos Inmunodeficiencia"
* #482 "Obesidad Mórbida VIRAFLU Adultos Obesidad Mórbida"
* #483 "Respiratorio VIRAFLU Adultos Respiratorio"
* #484 "Esquema de Excepción Fluxvir adyuvantada Otros"
* #485 "Esquema de Excepción VIRAFLU Pediátrica Otros"
* #486 "Esquema de Excepción VIRAFLU Adultos Otros"
* #487 "Personal de Salud AstraZeneca ChAdOx1 S recombinante Personal de Salud"
* #488 "Personal Estratégico AstraZeneca ChAdOx1 S recombinante Personal Estratégico"
* #489 "Personas de 60 o más años AstraZeneca ChAdOx1 S recombinante Personas de 60 o más años"
* #490 "Personas de 18 a 59 años con Factores de Riesgo AstraZeneca ChAdOx1 S recombinante Personas de 18 a 59 años con Factores de Riesgo"
* #491 "Esquema de Excepción AstraZeneca ChAdOx1 S recombinante Otros"
* #492 "Entre 1 y 6 años BCG Otros"
* #493 "Mayor o igual a 1 año IPV SALK Otros"
* #494 "Mayor de 1 año Quintuple Otros"
* #495 "Mayor o igual de 2 años Quintuple Otros"
* #496 "Mayor o igual de 24 meses Meningocócica Tetravalente Conjugada Otros"
* #497 "Mayor o igual de 12 años Meningocócica Tetravalente Conjugada Otros"
* #498 "Mayor o igual de 2 años Varicela Otros"
* #499 "Entre 2 y 14 años Hepatitis A Otros"
* #500 "Mayor de 1 año Neumococo Conjugada VCN 13 Otros"
* #501 "Mayor de 2 años Neumococo Conjugada VCN 13 Otros"
* #502 "Mayor o igual de 2 años Triple Viral Otros"
* #503 "Mayor de 6 años Triple Viral Otros"
* #504 "Mayor o igual a 12 años MUJERES VPH Cuadrivalente Otros"
* #505 "Mayor o igual a 12 años VARONES VPH Cuadrivalente Otros"
* #506 "Mayor o igual de 12 años Triple Bacteriana Acelular Otros"
* #507 "Mayor o igual de 2 años Fiebre Amarilla Otros"
* #508 "Mayor o igual de 12 años Fiebre Amarilla Otros"
* #509 "Mayor de 5 años IPV SALK Otros"
* #510 "1 año Meningocócica Tetravalente Conjugada Otros"


ValueSet: NomivacEsquemaVS
Id: NomivacEsquemaVS
Title: "Esquemas de Vacunacion para NOMIVAC"
Description: "Esquemas de Vacunacion para NOMIVAC"
* ^url = "http://fhir.msal.gob.ar/core/ValueSet/NomivacEsquemaVS"
* ^version = "0.5.0"
* ^name = "NomivacEsquemaVS"
* ^title = "Esquemas de Vacunacion para NOMIVAC"
* ^status = #active
* ^date = "2021-07-18T16:43:39-03:00"
* ^publisher = "DNSIS - Ministerio de Salud - Rep. Argentina / HL7 Argentina"
* ^contact[0].name = "DNSIS - Ministerio de Salud - Rep. Argentina / HL7 Argentina"
* ^contact[=].telecom[0].system = #url
* ^contact[=].telecom[=].value = "https://www.argentina.gob.ar/salud/digital"
* ^contact[=].telecom[+].system = #email
* ^contact[=].telecom[=].value = "privadadngiss@msal.gov.ar"
* ^experimental = false
* ^language = #es-AR

* codes from system NomivacEsquemaCS